import type { Job, Quote, SiteVisit, Worker } from "@/types/ops";
import {
  EMPTY_INVENTORY,
  EMPTY_SPECIAL_ITEMS,
  formatInventorySummary,
} from "@/types/ops";
import { splitSchedule } from "@/lib/calendar/schedule";

const PLACEHOLDER_PHOTO =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==";

export const SEED_WORKERS: Worker[] = [
  { id: "w-owner", name: "Majiteľ NSVS-E", role: "owner" },
  { id: "w-field-1", name: "Martin Kováč", role: "field" },
  { id: "w-field-2", name: "Peter Horváth", role: "field" },
  { id: "w-crew-1", name: "Ján Novák", role: "crew" },
  { id: "w-crew-2", name: "Tomáš Belko", role: "crew" },
];

function atDay(base: Date, dayOffset: number, hour: number): string {
  const d = new Date(base);
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() + dayOffset);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

/**
 * When we're in the last days of a month, seed into the *next* month
 * (e.g. 30 Sep → October) so the calendar looks busy ahead.
 */
export function getDemoCalendarMonth(base = new Date()): {
  year: number;
  month: number;
} {
  const lastDay = new Date(base.getFullYear(), base.getMonth() + 1, 0).getDate();
  if (base.getDate() >= lastDay - 2) {
    const next = new Date(base.getFullYear(), base.getMonth() + 1, 1);
    return { year: next.getFullYear(), month: next.getMonth() };
  }
  return { year: base.getFullYear(), month: base.getMonth() };
}

/** First day of the demo calendar month (noon local). */
export function getDemoCalendarAnchor(base = new Date()): Date {
  const { year, month } = getDemoCalendarMonth(base);
  return new Date(year, month, 1, 12, 0, 0, 0);
}

/** Day-of-month inside the demo calendar month. */
function atSeedMonthDay(
  base: Date,
  dayOfMonth: number,
  hour: number,
  minute = 0,
): string {
  const { year, month } = getDemoCalendarMonth(base);
  const last = new Date(year, month + 1, 0).getDate();
  const d = new Date(
    year,
    month,
    Math.min(Math.max(1, dayOfMonth), last),
    hour,
    minute,
    0,
    0,
  );
  return d.toISOString();
}

export function buildSeedBundle(now = new Date()) {
  const v1Counts = {
    ...EMPTY_INVENTORY,
    krabice: 15,
    skrina: 2,
    spotrebice: 2,
  };
  const v1Custom = "Pohovka, chladnička";
  const v2Counts = {
    ...EMPTY_INVENTORY,
    stol: 12,
    stolicky: 24,
    skrina: 4,
    krabice: 40,
  };
  const v2Custom = "Servery (2 ks)";
  const vWaitCounts = {
    ...EMPTY_INVENTORY,
    krabice: 20,
    postel: 1,
    skrina: 1,
    spotrebice: 1,
  };
  const a1Counts = { ...EMPTY_INVENTORY, krabice: 20, postel: 1, skrina: 1 };
  const a2Counts = { ...EMPTY_INVENTORY, krabice: 25, stol: 1 };
  const a2Custom = "2 pohovky, klavír";
  const a3Counts = {
    ...EMPTY_INVENTORY,
    stol: 8,
    stolicky: 16,
  };
  const a3Custom = "Trezor, archív";

  const b1Counts = {
    ...EMPTY_INVENTORY,
    krabice: 28,
    postel: 1,
    skrina: 2,
    stol: 1,
    stolicky: 4,
    spotrebice: 2,
  };
  const b1Custom = "Sťahovanie 2-izbového bytu · pohovka";
  const b2Counts = {
    ...EMPTY_INVENTORY,
    krabice: 35,
    postel: 2,
    skrina: 3,
    stol: 1,
    stolicky: 6,
    spotrebice: 3,
  };
  const b2Custom = "3-izbový byt s balkónom · pračka + sušička";
  const b3Counts = {
    ...EMPTY_INVENTORY,
    krabice: 18,
    postel: 1,
    skrina: 1,
    spotrebice: 1,
  };
  const b3Custom = "Garsónka · rozkladacia pohovka";
  const b4Counts = {
    ...EMPTY_INVENTORY,
    krabice: 42,
    postel: 2,
    skrina: 3,
    stol: 2,
    stolicky: 8,
    spotrebice: 4,
  };
  const b4Custom = "Sťahovanie 3-izbového bytu · jedáleň + detská izba";
  const b5Counts = {
    ...EMPTY_INVENTORY,
    krabice: 22,
    postel: 1,
    skrina: 2,
    stolicky: 4,
    spotrebice: 2,
  };
  const b5Custom = "2-izbový byt · bez výťahu, 3. poschodie";
  const b6Counts = {
    ...EMPTY_INVENTORY,
    krabice: 30,
    postel: 1,
    skrina: 2,
    stol: 1,
    spotrebice: 2,
  };
  const b6Custom = "Sťahovanie 2-izbového bytu s balkónom";
  const b7Counts = {
    ...EMPTY_INVENTORY,
    krabice: 16,
    postel: 1,
    skrina: 1,
    stol: 1,
    stolicky: 2,
  };
  const b7Custom = "1,5-izbový byt · knižnica";

  const visits: SiteVisit[] = [
    {
      id: "sv-pending-1",
      createdById: "w-field-1",
      createdByName: "Martin Kováč",
      status: "pending_pricing",
      customerName: "Eva Horváthová",
      customerPhone: "+421 905 111 222",
      addressFrom: "Račianska 12, Bratislava",
      addressTo: "Námestie slobody 3, Bratislava",
      floorFrom: 4,
      floorTo: 2,
      elevatorFrom: false,
      elevatorTo: true,
      parkingFrom: "10-50m",
      parkingTo: "0-10m",
      inventoryCounts: v1Counts,
      customItems: v1Custom,
      itemsList: formatInventorySummary(v1Counts, v1Custom),
      specialRequests: "Úzke schodisko, potrebný popruh na chladničku",
      specialItems: { ...EMPTY_SPECIAL_ITEMS, fragile: true },
      media: [
        {
          id: "m1",
          type: "photo",
          dataUrl: PLACEHOLDER_PHOTO,
          mimeType: "image/png",
          name: "obvyadka-1.png",
        },
        {
          id: "m2",
          type: "photo",
          dataUrl: PLACEHOLDER_PHOTO,
          mimeType: "image/png",
          name: "obvyadka-2.png",
        },
      ],
      visitAt: atDay(now, -1, 14),
      createdAt: atDay(now, -1, 15),
      updatedAt: atDay(now, -1, 15),
    },
    {
      id: "sv-waiting-1",
      createdById: "w-field-2",
      createdByName: "Peter Horváth",
      status: "waiting_for_client",
      customerName: "Firma SoftLab s.r.o.",
      customerPhone: "+421 2 5555 100",
      addressFrom: "Einsteinova 24, Bratislava",
      addressTo: "Pribinova 8, Bratislava",
      floorFrom: 6,
      floorTo: 5,
      elevatorFrom: true,
      elevatorTo: true,
      parkingFrom: "0-10m",
      parkingTo: "0-10m",
      inventoryCounts: v2Counts,
      customItems: v2Custom,
      itemsList: formatInventorySummary(v2Counts, v2Custom),
      specialRequests: "Sťahovanie mimo pracovného času, od 18:00",
      specialItems: { ...EMPTY_SPECIAL_ITEMS, safe: true, assembly: true },
      media: [
        {
          id: "m3",
          type: "photo",
          dataUrl: PLACEHOLDER_PHOTO,
          mimeType: "image/png",
          name: "kancelaria.png",
        },
      ],
      visitAt: atDay(now, 0, 10),
      createdAt: atDay(now, 0, 11),
      updatedAt: atDay(now, 0, 16),
    },
    {
      id: "sv-pending-2",
      createdById: "w-field-1",
      createdByName: "Martin Kováč",
      status: "pending_pricing",
      customerName: "Jana Belková",
      customerPhone: "+421 904 111 000",
      addressFrom: "Tomášikova 12, Bratislava",
      addressTo: "Vajnorská 100, Bratislava",
      floorFrom: 2,
      floorTo: 0,
      elevatorFrom: true,
      elevatorTo: false,
      parkingFrom: "0-10m",
      parkingTo: "10-50m",
      inventoryCounts: vWaitCounts,
      customItems: "",
      itemsList: formatInventorySummary(vWaitCounts, ""),
      specialRequests: "",
      specialItems: { ...EMPTY_SPECIAL_ITEMS },
      media: [],
      visitAt: atDay(now, -2, 11),
      createdAt: atDay(now, -2, 12),
      updatedAt: atDay(now, -2, 12),
    },
    {
      id: "sv-accepted-1",
      createdById: "w-field-1",
      createdByName: "Martin Kováč",
      status: "accepted_job",
      customerName: "Michal Tóth",
      customerPhone: "+421 918 333 444",
      addressFrom: "Dunajská 5, Bratislava",
      addressTo: "Karloveská 60, Bratislava",
      floorFrom: 3,
      floorTo: 1,
      elevatorFrom: true,
      elevatorTo: false,
      parkingFrom: "0-10m",
      parkingTo: "10-50m",
      inventoryCounts: a1Counts,
      customItems: "Pračka",
      itemsList: formatInventorySummary(a1Counts, "Pračka"),
      specialRequests: "Parkovanie pred vchodom dohodnuté",
      specialItems: { ...EMPTY_SPECIAL_ITEMS },
      media: [
        {
          id: "m4",
          type: "photo",
          dataUrl: PLACEHOLDER_PHOTO,
          mimeType: "image/png",
          name: "byt.png",
        },
      ],
      visitAt: atDay(now, -5, 11),
      createdAt: atDay(now, -5, 12),
      updatedAt: atDay(now, -3, 9),
    },
    {
      id: "sv-accepted-2",
      createdById: "w-field-2",
      createdByName: "Peter Horváth",
      status: "accepted_job",
      customerName: "Zuzana Kráľová",
      customerPhone: "+421 903 777 888",
      addressFrom: "Šancová 88, Bratislava",
      addressTo: "Ružinovská 1, Bratislava",
      floorFrom: 2,
      floorTo: 5,
      elevatorFrom: true,
      elevatorTo: true,
      parkingFrom: "10-50m",
      parkingTo: "10-50m",
      inventoryCounts: a2Counts,
      customItems: a2Custom,
      itemsList: formatInventorySummary(a2Counts, a2Custom),
      specialRequests: "Klavír cez výťah – rezervované",
      specialItems: { ...EMPTY_SPECIAL_ITEMS, piano: true, fragile: true },
      media: [],
      visitAt: atDay(now, -8, 10),
      createdAt: atDay(now, -8, 11),
      updatedAt: atDay(now, -6, 14),
    },
    {
      id: "sv-accepted-3",
      createdById: "w-field-1",
      createdByName: "Martin Kováč",
      status: "accepted_job",
      customerName: "Office Move SK",
      customerPhone: "+421 911 222 333",
      addressFrom: "Mlynské nivy 16, Bratislava",
      addressTo: "Tomášikova 30, Bratislava",
      floorFrom: 4,
      floorTo: 3,
      elevatorFrom: true,
      elevatorTo: true,
      parkingFrom: "0-10m",
      parkingTo: "0-10m",
      inventoryCounts: a3Counts,
      customItems: a3Custom,
      itemsList: formatInventorySummary(a3Counts, a3Custom),
      specialRequests: "Trezor – 2 osoby extra",
      specialItems: { ...EMPTY_SPECIAL_ITEMS, safe: true, assembly: true },
      media: [],
      visitAt: atDay(now, -10, 9),
      createdAt: atDay(now, -10, 10),
      updatedAt: atDay(now, -7, 12),
    },
    {
      id: "sv-accepted-4",
      createdById: "w-field-1",
      createdByName: "Martin Kováč",
      status: "accepted_job",
      customerName: "Lucia Hrušková",
      customerPhone: "+421 905 441 220",
      addressFrom: "Panónska cesta 17, Petržalka, Bratislava",
      addressTo: "Jasovská 8, Petržalka, Bratislava",
      floorFrom: 3,
      floorTo: 5,
      elevatorFrom: false,
      elevatorTo: true,
      parkingFrom: "10-50m",
      parkingTo: "0-10m",
      inventoryCounts: b1Counts,
      customItems: b1Custom,
      itemsList: formatInventorySummary(b1Counts, b1Custom),
      specialRequests: "3. poschodie bez výťahu – popruhy a vozík povinné",
      specialItems: { ...EMPTY_SPECIAL_ITEMS, assembly: true },
      media: [],
      visitAt: atSeedMonthDay(now, 4, 10),
      createdAt: atSeedMonthDay(now, 4, 11),
      updatedAt: atSeedMonthDay(now, 5, 9),
    },
    {
      id: "sv-accepted-5",
      createdById: "w-field-2",
      createdByName: "Peter Horváth",
      status: "accepted_job",
      customerName: "Andrej Štefánik",
      customerPhone: "+421 918 662 110",
      addressFrom: "Ružinovská 42, Ružinov, Bratislava",
      addressTo: "Ostredková 14, Ružinov, Bratislava",
      floorFrom: 6,
      floorTo: 2,
      elevatorFrom: true,
      elevatorTo: true,
      parkingFrom: "0-10m",
      parkingTo: "10-50m",
      inventoryCounts: b2Counts,
      customItems: b2Custom,
      itemsList: formatInventorySummary(b2Counts, b2Custom),
      specialRequests: "3-izbový byt s balkónom – demontáž postelí",
      specialItems: { ...EMPTY_SPECIAL_ITEMS, fragile: true, assembly: true },
      media: [],
      visitAt: atSeedMonthDay(now, 6, 9),
      createdAt: atSeedMonthDay(now, 6, 10),
      updatedAt: atSeedMonthDay(now, 7, 14),
    },
    {
      id: "sv-accepted-6",
      createdById: "w-field-1",
      createdByName: "Martin Kováč",
      status: "accepted_job",
      customerName: "Mária Vargová",
      customerPhone: "+421 903 118 774",
      addressFrom: "Ventúrska 9, Staré Mesto, Bratislava",
      addressTo: "Klariská 4, Staré Mesto, Bratislava",
      floorFrom: 2,
      floorTo: 3,
      elevatorFrom: false,
      elevatorTo: false,
      parkingFrom: "50m+",
      parkingTo: "50m+",
      inventoryCounts: b3Counts,
      customItems: b3Custom,
      itemsList: formatInventorySummary(b3Counts, b3Custom),
      specialRequests: "Úzka ulica v Starom Meste – krátke parkovanie",
      specialItems: { ...EMPTY_SPECIAL_ITEMS, fragile: true },
      media: [],
      visitAt: atSeedMonthDay(now, 8, 11),
      createdAt: atSeedMonthDay(now, 8, 12),
      updatedAt: atSeedMonthDay(now, 9, 10),
    },
    {
      id: "sv-accepted-7",
      createdById: "w-field-2",
      createdByName: "Peter Horváth",
      status: "accepted_job",
      customerName: "Peter a Jana Novákovci",
      customerPhone: "+421 911 550 303",
      addressFrom: "Karloveská 34, Karlova Ves, Bratislava",
      addressTo: "Dúbravská cesta 2, Dúbravka, Bratislava",
      floorFrom: 4,
      floorTo: 1,
      elevatorFrom: true,
      elevatorTo: true,
      parkingFrom: "0-10m",
      parkingTo: "0-10m",
      inventoryCounts: b4Counts,
      customItems: b4Custom,
      itemsList: formatInventorySummary(b4Counts, b4Custom),
      specialRequests: "Ranný slot – detská izba ako prvá",
      specialItems: { ...EMPTY_SPECIAL_ITEMS, assembly: true },
      media: [],
      visitAt: atSeedMonthDay(now, 10, 9),
      createdAt: atSeedMonthDay(now, 10, 10),
      updatedAt: atSeedMonthDay(now, 11, 16),
    },
    {
      id: "sv-accepted-8",
      createdById: "w-field-1",
      createdByName: "Martin Kováč",
      status: "accepted_job",
      customerName: "Tomáš Greš",
      customerPhone: "+421 904 221 889",
      addressFrom: "Saratovská 12, Dúbravka, Bratislava",
      addressTo: "Borská 5, Dúbravka, Bratislava",
      floorFrom: 3,
      floorTo: 0,
      elevatorFrom: false,
      elevatorTo: false,
      parkingFrom: "10-50m",
      parkingTo: "0-10m",
      inventoryCounts: b5Counts,
      customItems: b5Custom,
      itemsList: formatInventorySummary(b5Counts, b5Custom),
      specialRequests: "Bez výťahu, 3. poschodie – 3 pracovníci",
      specialItems: { ...EMPTY_SPECIAL_ITEMS },
      media: [],
      visitAt: atSeedMonthDay(now, 12, 10),
      createdAt: atSeedMonthDay(now, 12, 11),
      updatedAt: atSeedMonthDay(now, 13, 9),
    },
    {
      id: "sv-accepted-9",
      createdById: "w-field-2",
      createdByName: "Peter Horváth",
      status: "accepted_job",
      customerName: "Katarína Beláňová",
      customerPhone: "+421 917 330 441",
      addressFrom: "Černyševského 26, Petržalka, Bratislava",
      addressTo: "Romanova 18, Petržalka, Bratislava",
      floorFrom: 7,
      floorTo: 4,
      elevatorFrom: true,
      elevatorTo: true,
      parkingFrom: "0-10m",
      parkingTo: "10-50m",
      inventoryCounts: b6Counts,
      customItems: b6Custom,
      itemsList: formatInventorySummary(b6Counts, b6Custom),
      specialRequests: "Popoludňajší termín – zákazníčka po 14:00",
      specialItems: { ...EMPTY_SPECIAL_ITEMS, fragile: true },
      media: [],
      visitAt: atSeedMonthDay(now, 14, 15),
      createdAt: atSeedMonthDay(now, 14, 16),
      updatedAt: atSeedMonthDay(now, 15, 10),
    },
    {
      id: "sv-accepted-10",
      createdById: "w-field-1",
      createdByName: "Martin Kováč",
      status: "accepted_job",
      customerName: "Igor Polák",
      customerPhone: "+421 902 774 556",
      addressFrom: "Štúrova 11, Staré Mesto, Bratislava",
      addressTo: "Líščie údolie 7, Karlova Ves, Bratislava",
      floorFrom: 1,
      floorTo: 2,
      elevatorFrom: true,
      elevatorTo: false,
      parkingFrom: "10-50m",
      parkingTo: "50m+",
      inventoryCounts: b7Counts,
      customItems: b7Custom,
      itemsList: formatInventorySummary(b7Counts, b7Custom),
      specialRequests: "Knižnica – krehké sklo, deky",
      specialItems: { ...EMPTY_SPECIAL_ITEMS, fragile: true, assembly: true },
      media: [],
      visitAt: atSeedMonthDay(now, 18, 10),
      createdAt: atSeedMonthDay(now, 18, 11),
      updatedAt: atSeedMonthDay(now, 19, 12),
    },
  ];

  const quotes: Quote[] = [
    {
      id: "q-waiting-1",
      siteVisitId: "sv-waiting-1",
      priceEur: 890,
      internalNotes: "PDF odoslané – čakáme na klienta",
      pdfDataUrl: null,
      status: "sent",
      pricedAt: atDay(now, 0, 16),
      pricedByName: "Majiteľ NSVS-E",
    },
    {
      id: "q-1",
      siteVisitId: "sv-accepted-1",
      priceEur: 380,
      internalNotes: "Štandardný byt, výťah na odchode",
      pdfDataUrl: null,
      status: "accepted",
      pricedAt: atDay(now, -4, 16),
      pricedByName: "Majiteľ NSVS-E",
    },
    {
      id: "q-2",
      siteVisitId: "sv-accepted-2",
      priceEur: 650,
      internalNotes: "Klavír + krehký nábytok",
      pdfDataUrl: null,
      status: "accepted",
      pricedAt: atDay(now, -6, 15),
      pricedByName: "Majiteľ NSVS-E",
    },
    {
      id: "q-3",
      siteVisitId: "sv-accepted-3",
      priceEur: 720,
      internalNotes: "Firemné + trezor",
      pdfDataUrl: null,
      status: "accepted",
      pricedAt: atDay(now, -7, 11),
      pricedByName: "Majiteľ NSVS-E",
    },
    {
      id: "q-4",
      siteVisitId: "sv-accepted-4",
      priceEur: 320,
      internalNotes: "2-izbový · Petržalka bez výťahu",
      pdfDataUrl: null,
      status: "accepted",
      pricedAt: atSeedMonthDay(now, 5, 10),
      pricedByName: "Majiteľ NSVS-E",
    },
    {
      id: "q-5",
      siteVisitId: "sv-accepted-5",
      priceEur: 580,
      internalNotes: "3-izbový Ružinov + spotrebiče",
      pdfDataUrl: null,
      status: "accepted",
      pricedAt: atSeedMonthDay(now, 7, 15),
      pricedByName: "Majiteľ NSVS-E",
    },
    {
      id: "q-6",
      siteVisitId: "sv-accepted-6",
      priceEur: 250,
      internalNotes: "Garsónka Staré Mesto",
      pdfDataUrl: null,
      status: "accepted",
      pricedAt: atSeedMonthDay(now, 9, 11),
      pricedByName: "Majiteľ NSVS-E",
    },
    {
      id: "q-7",
      siteVisitId: "sv-accepted-7",
      priceEur: 650,
      internalNotes: "3-izbový Karlova Ves → Dúbravka",
      pdfDataUrl: null,
      status: "accepted",
      pricedAt: atSeedMonthDay(now, 11, 17),
      pricedByName: "Majiteľ NSVS-E",
    },
    {
      id: "q-8",
      siteVisitId: "sv-accepted-8",
      priceEur: 410,
      internalNotes: "Dúbravka · 3. poschodie bez výťahu",
      pdfDataUrl: null,
      status: "accepted",
      pricedAt: atSeedMonthDay(now, 13, 10),
      pricedByName: "Majiteľ NSVS-E",
    },
    {
      id: "q-9",
      siteVisitId: "sv-accepted-9",
      priceEur: 390,
      internalNotes: "Petržalka popoludnie – busy day s garsónkou",
      pdfDataUrl: null,
      status: "accepted",
      pricedAt: atSeedMonthDay(now, 15, 11),
      pricedByName: "Majiteľ NSVS-E",
    },
    {
      id: "q-10",
      siteVisitId: "sv-accepted-10",
      priceEur: 470,
      internalNotes: "Staré Mesto → Karlova Ves",
      pdfDataUrl: null,
      status: "accepted",
      pricedAt: atSeedMonthDay(now, 19, 13),
      pricedByName: "Majiteľ NSVS-E",
    },
  ];

  const jobs: Job[] = [
    {
      id: "job-1",
      quoteId: "q-1",
      siteVisitId: "sv-accepted-1",
      startsAt: atSeedMonthDay(now, 8, 8),
      endsAt: atSeedMonthDay(now, 8, 12),
      ...splitSchedule(atSeedMonthDay(now, 8, 8)),
      crewInstructions: "Priniesť popruhy a vozík. Zákazník na mieste od 7:45.",
      status: "scheduled",
      finalAmountEur: 380,
      assignedWorkerIds: ["w-crew-1", "w-crew-2", "w-field-1"],
      completedAt: null,
    },
    {
      id: "job-2",
      quoteId: "q-2",
      siteVisitId: "sv-accepted-2",
      startsAt: atSeedMonthDay(now, 16, 9),
      endsAt: atSeedMonthDay(now, 16, 14),
      ...splitSchedule(atSeedMonthDay(now, 16, 9)),
      crewInstructions: "Klavír – popruhy a deky. Parkovanie na Šancovej.",
      status: "scheduled",
      finalAmountEur: 650,
      assignedWorkerIds: ["w-crew-1", "w-crew-2", "w-field-2"],
      completedAt: null,
    },
    {
      id: "job-3",
      quoteId: "q-3",
      siteVisitId: "sv-accepted-3",
      startsAt: atSeedMonthDay(now, 28, 7),
      endsAt: atSeedMonthDay(now, 28, 13),
      ...splitSchedule(atSeedMonthDay(now, 28, 7)),
      crewInstructions: "Trezor 2 osoby. Montáž stolov na mieste.",
      status: "scheduled",
      finalAmountEur: 720,
      assignedWorkerIds: ["w-crew-1", "w-crew-2"],
      completedAt: null,
    },
    {
      id: "job-4",
      quoteId: "q-4",
      siteVisitId: "sv-accepted-4",
      startsAt: atSeedMonthDay(now, 5, 8),
      endsAt: atSeedMonthDay(now, 5, 12),
      ...splitSchedule(atSeedMonthDay(now, 5, 8)),
      crewInstructions:
        "Sťahovanie 2-izbového bytu · Petržalka, 3. poschodie bez výťahu.",
      status: "scheduled",
      finalAmountEur: 320,
      assignedWorkerIds: ["w-crew-1", "w-crew-2", "w-field-1"],
      completedAt: null,
    },
    {
      id: "job-5",
      quoteId: "q-5",
      siteVisitId: "sv-accepted-5",
      startsAt: atSeedMonthDay(now, 12, 8),
      endsAt: atSeedMonthDay(now, 12, 13),
      ...splitSchedule(atSeedMonthDay(now, 12, 8)),
      crewInstructions:
        "3-izbový byt s balkónom · Ružinov. Demontáž postelí na mieste.",
      status: "scheduled",
      finalAmountEur: 580,
      assignedWorkerIds: ["w-crew-1", "w-crew-2", "w-field-2"],
      completedAt: null,
    },
    {
      id: "job-6",
      quoteId: "q-6",
      siteVisitId: "sv-accepted-6",
      startsAt: atSeedMonthDay(now, 1, 8),
      endsAt: atSeedMonthDay(now, 1, 11),
      ...splitSchedule(atSeedMonthDay(now, 1, 8)),
      crewInstructions:
        "1. október · ranný slot 08:00 Staré Mesto (Ventúrska).",
      status: "scheduled",
      finalAmountEur: 250,
      assignedWorkerIds: ["w-crew-1", "w-field-1"],
      completedAt: null,
    },
    {
      id: "job-7",
      quoteId: "q-9",
      siteVisitId: "sv-accepted-9",
      startsAt: atSeedMonthDay(now, 1, 14),
      endsAt: atSeedMonthDay(now, 1, 18),
      ...splitSchedule(atSeedMonthDay(now, 1, 14)),
      crewInstructions:
        "1. október · popoludnie 14:00 Petržalka – busy day s ranným slotom.",
      status: "scheduled",
      finalAmountEur: 390,
      assignedWorkerIds: ["w-crew-2", "w-field-2"],
      completedAt: null,
    },
    {
      id: "job-8",
      quoteId: "q-7",
      siteVisitId: "sv-accepted-7",
      startsAt: atSeedMonthDay(now, 20, 8),
      endsAt: atSeedMonthDay(now, 20, 14),
      ...splitSchedule(atSeedMonthDay(now, 20, 8)),
      crewInstructions:
        "Karlova Ves → Dúbravka · 3-izbový, detská izba ako prvá.",
      status: "scheduled",
      finalAmountEur: 650,
      assignedWorkerIds: ["w-crew-1", "w-crew-2", "w-field-1"],
      completedAt: null,
    },
    {
      id: "job-9",
      quoteId: "q-8",
      siteVisitId: "sv-accepted-8",
      startsAt: atSeedMonthDay(now, 24, 9),
      endsAt: atSeedMonthDay(now, 24, 13),
      ...splitSchedule(atSeedMonthDay(now, 24, 9)),
      crewInstructions: "Dúbravka · 3. poschodie bez výťahu, 3 ľudia.",
      status: "scheduled",
      finalAmountEur: 410,
      assignedWorkerIds: ["w-crew-1", "w-crew-2", "w-field-2"],
      completedAt: null,
    },
    {
      id: "job-10",
      quoteId: "q-10",
      siteVisitId: "sv-accepted-10",
      startsAt: atSeedMonthDay(now, 30, 8),
      endsAt: atSeedMonthDay(now, 30, 12),
      ...splitSchedule(atSeedMonthDay(now, 30, 8)),
      crewInstructions:
        "Staré Mesto → Karlova Ves · knižnica, krehké sklo, deky.",
      status: "scheduled",
      finalAmountEur: 470,
      assignedWorkerIds: ["w-crew-1", "w-crew-2"],
      completedAt: null,
    },
    {
      id: "job-done-1",
      quoteId: "q-1",
      siteVisitId: "sv-accepted-1",
      startsAt: atDay(now, -12, 9),
      endsAt: atDay(now, -12, 13),
      ...splitSchedule(atDay(now, -12, 9)),
      crewInstructions: "Dokončená ukážková zákazka pre demo financie.",
      status: "completed",
      finalAmountEur: 420,
      assignedWorkerIds: ["w-crew-1", "w-crew-2"],
      completedAt: atDay(now, -12, 13),
    },
    {
      id: "job-done-2",
      quoteId: "q-1",
      siteVisitId: "sv-accepted-1",
      startsAt: atDay(now, -28, 8),
      endsAt: atDay(now, -28, 14),
      ...splitSchedule(atDay(now, -28, 8)),
      crewInstructions: "Firemné sťahovanie – dokončené.",
      status: "completed",
      finalAmountEur: 890,
      assignedWorkerIds: ["w-crew-1", "w-crew-2", "w-field-2"],
      completedAt: atDay(now, -28, 14),
    },
  ];

  return { visits, quotes, jobs };
}

export const SEED_VISITS = buildSeedBundle(
  new Date("2026-09-25T10:00:00"),
).visits;
export const SEED_QUOTES = buildSeedBundle(
  new Date("2026-09-25T10:00:00"),
).quotes;
export const SEED_JOBS = buildSeedBundle(new Date("2026-09-25T10:00:00")).jobs;
